apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress-controller
  namespace: nginx-ingress
spec:
  chart:
    spec:
      chart: nginx-ingress-controller
      version: 9.x
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: nginx-ingress-controller
  valuesFrom:
  - kind: ConfigMap
    name: nginx-ingress-controller-helm-chart-value-overrides
    valuesKey: values.yaml # This is the default, but best to be explicit for clarity
